export const API_ENDPOINTS = {
  LOGIN: '/login',
  REGISTER: '/register',
  LOGOUT: '/logout',
  FORGET_PASSWORD: '/forget-password',
  CATEGORIES: '/category/',
  SUBCATEGORIES:'/subcategorys/',
  DIETARY: '/dietary.json',
  BRANDS: '/brands.json',
  PRODUCTS: '/products/',
  PRODUCT: '/product/',
  RELATED_PRODUCTS: '/products/',
  FLASH_SELL_PRODUCTS: '/products/',
  BEST_SELLER_PRODUCTS: '/products/',
  NEW_ARRIVAL_PRODUCTS: '/products/',
  POPULAR_PRODUCTS: '/products/',
  ELETRONIC_PRODUCTS: '/products/',
  FASHION_PRODUCTS: '/products/',
  ELECTRONIC_CATEGORY: '/category_electronic.json',
  PHONES_CATEGORY: '/category_phones.json',
  COMPUTER_CATEGORY: '/category_computer.json',
  TOPSELL_CATEGORY: '/categories_topsell.json',
  CLOTH_CATEGORY: '/category_cloth.json',
  SEARCH: '/products/',
  ORDERS: '/orders.json',
  ORDER: '/order.json',
  ORDER_STATUS: '/order-status.json',
  ADDRESS: '/address.json',
  PAYMENT: '/payment.json',
  CONTACT: '/contact.json',
  SHOP: '/shop.json',
  SHOPS: '/shops.json',
  WISHLIST: '/wishlist.json',
  BLOGS: '/blog.json',
  BLOGDETAILS: '/blogDetails.json',
  THIS_WEEK_PRODUCTS: '/products/',
  TOPSELL_PRODUCTS: '/products/',
};
